version: "2"
services:
  chromedriver:
    image: charsbar/docker-chromedriver
    expose:
      - "9515"
    ports:
      - "9515:9515"
    networks:
      my_net:
    entrypoint: [chromedriver, --headless, --no-sandbox, --disable-gpu, --url-base=wd/hub, --whitelisted-ips, --verbose]
  test:
    image: $TEST_IMAGE
    volumes:
      - $PWD:/mt
    working_dir:
      /mt
    depends_on:
      - chromedriver
    networks:
      my_net:
    command: >-
      bash -c "$TEST_COMMAND"
networks:
  my_net:
    driver: bridge